[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
# Distribution name (what you "pip install"). Can be hyphenated; import remains `dendra_models`.
name = "dendra-models"
dynamic = ["version"]
description = "Models for Dendra"
readme = "README.md"
requires-python = ">=3.9"
license = { file = "LICENSE" }
authors = [{ name = "Minhaj Hussain", email = "minhaj.hussain@duke.edu" }]
dependencies = [
  "dendra"
]

[project.optional-dependencies]
pyfibers-validation = [
  "pyfibers==0.9.0",
  "matplotlib>=3.8",
  "numpy>=1.24",
]

# Optional but nice-to-have
keywords = ["neuroscience", "models", "dendra"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

[tool.setuptools]
# Tell setuptools that packages live under src/
package-dir = { "" = "src" }

[tool.setuptools.dynamic]
version = {attr = "dendra_models.__version__"}

[tool.setuptools.packages.find]
# Find packages only under src, and include your package namespace
where = ["src"]
include = ["dendra_models*"]

[tool.setuptools.package-data]
# patterns are relative to the *package root* (`src/dendra_models`)
dendra_models = [
  "models/**/*.pt",
  "models/**/*.gml"
]

[tool.pytest.ini_options]
filterwarnings = [
  "error:Mechanism[.]ASSIGNED.*:DeprecationWarning",
]
